# Generated by Django 5.2.10 on 2026-01-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('severity', models.IntegerField(default=0)),
                ('entity_type', models.CharField(max_length=10)),
                ('entity_value', models.CharField(max_length=150)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=150)),
                ('src_ip', models.CharField(max_length=45)),
                ('action', models.CharField(max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.ingestionjob')),
            ],
        ),
    ]
