# Generated by Django 5.2.10 on 2026-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='mitre_tactic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
