# Generated by Django 5.2.10 on 2026-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_mitre_tactic'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='mitre_technique_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_technique_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
